version: '3'

services:
  python_data_pipeline:
    network_mode: host
    container_name: data_pipeline
    image: python_data_pipeline
    build:
      context: ..
    env_file:
      - .env
    volumes:
      - ../:/src/
    working_dir: /src
    restart: always
    command: python3
    stdin_open: true
    tty: true
